# Generated by Django 5.1.1 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bestsalesimage_best_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbanner',
            name='image',
            field=models.ImageField(default='defalut.png', upload_to='uploads/first_banner/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SecondBannerImage',
        ),
    ]
