# Generated by Django 5.1.1 on 2024-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_secondbanner_image_delete_secondbannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdbanner',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads/first_banner/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ThirdBannerImage',
        ),
    ]
