# Generated by Django 5.1.1 on 2024-12-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_thirdbanner_image_delete_thirdbannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsalesimage',
            name='best_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_sales_images', to='core.bestsales'),
        ),
        migrations.AlterField(
            model_name='newarivalimage',
            name='new_arival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_arival_images', to='core.newarival'),
        ),
    ]
