# Generated by Django 5.1.1 on 2024-12-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bestsalesimage_best_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsalesimage',
            name='best_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.bestsales'),
        ),
        migrations.AlterField(
            model_name='newarivalimage',
            name='new_arival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.newarival'),
        ),
    ]
